language: java

sudo: false

jdk:
  - openjdk7
  - oraclejdk8

os:
  - linux


script:
  - mkdir -p bin
  - python build.py clean
  - python build.py build
  - python build.py run codeu.chat.TestRunner
